---
- hosts: webservers
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root

  roles:
#    - ansible_role_redis
#    - ansible_role_mailcatcher
#    - ansible_role_php72
#    - ansible_role_siege
#    - ansible_role_extra_repositories
    - ansible_role_python3
#    - ansible_role_magento23_commerce