---
- hosts: webservers
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root

  roles:
#    - ansible_role_docker_ce
    - ansible_role_rabbitmq
#    - ansible_role_php72
#    - ansible_role_git