---
- hosts: webservers
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root

#  pre_tasks:
#    - pause:
#        prompt: "What is your Magento public key?"
#      when: magento_public_key==''
#      register: magento_public_key
#
#    - pause:
#        prompt: "What is your Magento private key?"
#      when: magento_private_key==''
#      register: magento_private_key

  roles:
#    - ansible_role_redis
#    - ansible_role_mailcatcher
#    - ansible_role_php72
#    - ansible_role_siege
#    - ansible_role_extra_repositories
#    - ansible_role_python3
#    - ansible_role_nodejs
    - ansible_role_java8
    - ansible_role_elasticsearch
#    - ansible_role_magento23_commerce

#  vars_prompt:
#    - name: magento_public_key
#      prompt: "What is your Magento public key?"
#      private: no
#
#    - name: magento_private_key
#      prompt: "What is your Magento private key?"
#      private: no