---
- hosts: webservers
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root

  roles:
    - ansible_role_extra_repositories # Enable EPEL and Remi's repositories
    - ansible_role_common
    - ansible_role_git
    - ansible_role_apache2
    - ansible_role_selinux # disable SELinux
    - ansible_role_php72
    - ansible_role_php72_xdebug
    - ansible_role_mysql
    - ansible_role_redis
    - ansible_role_rabbitmq
    - ansible_role_nodejs
    - ansible_role_mailcatcher
    - ansible_role_siege
    - ansible_role_java8
    - ansible_role_elasticsearch
    - ansible_role_magento23_commerce