---
- hosts: webservers
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root

#  pre_tasks:
#    - pause:
#        prompt: "What is your Magento public key?"
#      when: magento_public_key==''
#      register: magento_public_key
#
#    - pause:s
#        prompt: "What is your Magento private key?"
#      when: magento_private_key==''
#      register: magento_private_key

  roles:
    - ansible_role_extra_repositories # Enable EPEL and Remi's repositories
    - ansible_role_common
    - ansible_role_git
    - ansible_role_apache2
    - ansible_role_selinux # disable SELinux
    - ansible_role_php72
    - ansible_role_php72_xdebug
    - ansible_role_mysql
    - ansible_role_redis
    - ansible_role_rabbitmq
    - ansible_role_nodejs
    - ansible_role_mailcatcher
    - ansible_role_siege
    - ansible_role_java8
    - ansible_role_elasticsearch
    #- ansible_role_magento23_commerce
    - ansible_role_magento23_community
    - ansible_role_oh_my_zsh
      users:
        - username: vagrant
          oh_my_zsh:
            theme: ys
            plugins:
              - git
              - sudo